@baseUrl = http://localhost:3000/api/v1
@authToken = {{login.response.body.data.accessToken}}

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "student3@neon.com",
  "password": "Password123!",
  "name": "Etu Neon"
}

###
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "student3@neon.com",
  "password": "Password123!"
}

### HEALTH
GET {{baseUrl}}/health


### Crée un QCM
# @name createQcm
POST {{baseUrl}}/qcms
Content-Type: application/json

{
  "title": "Quiz Express et Prisma",
  "question1": {
    "text": "Que signifie API ?",
    "propositions": [
      { "text": "Application Programming Interface", "isCorrect": true },
      { "text": "Advanced Program Integration", "isCorrect": false },
      { "text": "Automated Process Interaction", "isCorrect": false }
    ]
  },
  "question2": {
    "text": "Quel port est utilisé par défaut dans cet exercice ?",
    "propositions": [
      { "text": "8080", "isCorrect": false },
      { "text": "3000", "isCorrect": true }
    ]
  }
}

@qcmId = {{createQcm.response.body.data.id}}

### Liste tous les QCMs
GET {{baseUrl}}/qcms


### Récupère un QCM par son id
GET {{baseUrl}}/qcms/{{qcmId}}


### Récupère la prochaine question d'un QCM
# @name getNextQuestion
GET {{baseUrl}}/qcms/{{qcmId}}/question
Authorization: Bearer {{authToken}}

@questionId = {{getNextQuestion.response.body.data.id}}
@propositionId = {{getNextQuestion.response.body.data.propositions[0].id}}


### Soumet une réponse
POST {{baseUrl}}/qcms/{{qcmId}}/response
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "questionId": "{{questionId}}",
  "propositionId": "{{propositionId}}"
}


### Récupère le résultat d'un QCM
GET {{baseUrl}}/qcms/{{qcmId}}/result
Authorization: Bearer {{authToken}}


### Supprime un QCM
DELETE {{baseUrl}}/qcms/{{qcmId}}